### ISSUE TITLE
Plans for Supporting V1 Message Format/Algorithms?

### ISSUE THREAD

**Issue by graytonio** [chainifynet/aws-encryption-sdk-go#156]
I am trying to work with some very old encrypted data and code that has not made the transition to the v2 formats with key commitment. We are working on migrating the data to v2 but we would still need to support v1 for a while are there any plans to support v1 as part of the module?
```[tasklist]
### Tasks
- [x] Serialisation/Deserialisation for Message V1
- [x] Support algorithms without HKDF for key derivation
- [x] Fix issue AES 192 frame size
- [x] Cover Message format V1 with tests
- [x] Cover new V1 format within E2E tests
- [ ] https://github.com/chainifynet/aws-encryption-sdk-go/pull/170
```

**Comment by wobondar** [comment]
@graytonio
Initially, we at @chainifynet had not planned to implement the V1 message format, as our focus was primarily on adopting and advancing with the V2 standards.

However, I could completely understand the challenges of transitioning legacy systems and data.

Could you provide more specific details to assess better our module's feasibility and scope of supporting V1? Specifically:

1. Which V1 algorithm IDs are you currently using or looking to support?
2. Is the Content Type you're dealing with non-framed or framed?

**Comment by graytonio** [comment]
We are primarily targeting algorithm ID `01 78` and framed data

**Comment by graytonio** [comment]
Ideally the goal would be to be able to enable `CommitmentPolicyRequireEncryptAllowDecrypt` which would allow us to start encrypting with v2 while still being able to read all data encrypted with v1. Currently it does not seem like this is possible.

**Comment by wobondar** [comment]
@graytonio
im working on V1 implementation, aiming to complete it by the end of this week.

**Comment by graytonio** [comment]
@wobondar Thank you for such a quick turn around on this can't wait to use it 🎉

**Comment by wobondar** [comment]
@graytonio 
I have just released version [v0.2.0](https://github.com/chainifynet/aws-encryption-sdk-go/releases/tag/v0.2.0). Could you please test it out and inform me of the results?

**Comment by graytonio** [comment]
From our initial testing it looks like the support is working as expected. Thank You so much 🎉
